spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: com.laoji.business.controller,com.laoji.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1
    port: 8848
# 开启 Feign 的 OKHttp 方式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: "*"
base:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret
