base:
  config:
    rocketmq:
      hostname: 127.0.0.1
      port: 9876
    nacos:
      hostname: 127.0.0.1
      port: 8848
spring:
  application:
    name: message-admin-login-log
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${base.config.rocketmq.hostname}:${base.config.rocketmq.port}
        bindings:
          admin-login-log-topic: {consumer.orderly: true}
      bindings:
        # consumer.maxAttempts
        # 消息最大可以被尝试消费的次数，包含第一次投递
        # 设为 1，表示不重试，注意该值必须大于 0
        admin-login-log-topic: {destination: admin-login-log-topic, content-type: text/plain, group: admin-login-log-group, consumer.maxAttempts: 1}
dubbo:
  scan:
    base-packages: com.laoji.message.consumer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}
server:
  port: 20001
